### ISSUE TITLE
When minibuffer window is active, background modeline in (previously) active window is off

### ISSUE THREAD

**Issue by apc** [rougier/nano-modeline#45] opened 2023-01-10 14:18 UTC
I'm not sure what controls the look of the modeline in the active window when the minibuffer window is active, but something seems off. I think the issue is that the right fringe background color is not modified, unlike the background color of the rest of the modeline: 

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/350504/211570236-64588056-0f08-4aaf-8cb6-87463ce3005d.png">

(This is using the built-in dichromancy theme, with `fringe-mode` set to `default`.)

It's even more noticeable if you increase the right fringe (here I set the right fringe to 80):

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/350504/211570883-c41510b3-a8a7-485b-9cc5-e397a04095b6.png">

I can reproduce in vanilla emacs after installing nano-modeline (by calling `package-install`) and evaluating the following buffer: 

```lisp
(fringe-mode '(4 . 80))
(setq nano-modeline-position 'bottom)
(nano-modeline-mode)
```

<img width="662" alt="image" src="https://user-images.githubusercontent.com/350504/211574410-ebdfc705-1480-49f9-8443-bb860d0482d1.png">

(For clarity, the screenshot is taken after splitting the frame in two and calling `switch-to-buffer`.)

**Comment by rougier** [comment] 2023-01-10 18:37
I do not modify the fringe, that might be the reason. But with vanilla emacs / default modeline, you have the same problem, do you?

**Comment by apc** [comment] 2023-01-10 21:15
I'm not sure I understand. In vanilla emacs with the default modeline, the modeline has a constant background even when the fringe has a different color from the default background. E.g., trying out 

```lisp
(fringe-mode '(4 . 80))
```

and then calling `switch-to-buffer` gives me this: 

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/350504/211660214-e92e68b6-10d7-45c8-bb64-b534dd8a2666.png">

Note the difference with what happens after installing `nano-modeline`, positioning the modeline at the bottom, activating `nano-modeline-mode`, and then calling `switch-to-buffer`: 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/350504/211661574-024f7a4d-e9cb-43a0-a355-13d21af49ad5.png">


The background only looks like this when the minibuffer is active. Otherwise, it looks as you'd expect: 

<img width="663" alt="image" src="https://user-images.githubusercontent.com/350504/211661511-4f2cd8ee-a7ae-4cce-a00b-5fb4276d2328.png">

From what I can tell, the problem is that when the minibuffer is active, part of the modeline is using the `mode-line-inactive` but the bit above the fringe on the right continues to use the `mode-line-active` face.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/350504/211663878-dead8dc8-9b47-4afa-b428-aa4be01f5922.png">

And changing the color of the fringe doesn't change the color of the segment of the modeline right above the right fringe, e.g.: 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/350504/211663959-034fcae2-3c9c-4da6-8643-060fea235dae.png">

**Comment by apc** [comment] 2023-01-10 21:20
PS: more evidence that this seems unrelated to the background color of the fringe: 

<img width="740" alt="image" src="https://user-images.githubusercontent.com/350504/211664894-4674e5ca-da5f-4023-8e39-27ff9e6f0768.png">

**Comment by rougier** [comment] 2023-01-11 06:52
I see. I think the problem is that the modeline stops at the right border instead of the right fringe border. I'll look into that. Or if you want to experiment, you can have a look at [line 490](https://github.com/rougier/nano-modeline/blob/master/nano-modeline.el#L490) and [pixel specifications](https://www.gnu.org/software/emacs/manual/html_node/elisp/Pixel-Specification.html). Mayeb replacing `right-margin` with `right-fringe` could do the trick.

**Comment by apc** [comment] 2023-01-11 21:50
That seems to do the trick! Maybe this will save you a bit of time: https://github.com/rougier/nano-modeline/pull/46

**Comment by aaronjensen** [comment] 2023-01-11 23:37
@apc see if you can reproduce it with my fork: https://github.com/aaronjensen/nano-modeline/blob/master/nano-modeline.el

**Comment by apc** [comment] 2023-01-12 17:27
@aaronjensen yes, I get the same behavior. From what I can tell, the problem is visible only when the faces `mode-line` and `mode-line-inactive` have different background colors. The faces `nano-modeline-active` and `nano-modeline-inactive` are inheriting the background colors from those two, and when the modeline doesn't extend all the way to the end of the fringe, you still see the background color of the `mode-line` face over the fringe.

**Comment by rougier** [comment] 2023-02-02 12:01
Isn't it the window divider that you see? Can you try to change the `window-divider` face to yellow to be sure?

**Comment by apc** [comment] 2023-02-03 02:56
I'm pretty sure it's not the window-divider. I think it's the scroll-bar. 

<img width="864" alt="image" src="https://user-images.githubusercontent.com/350504/216500702-3aa69110-deef-4fd2-91b0-91512e7ea4d4.png">

Look at the difference when I turn off `scroll-bar-mode`: 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/350504/216500953-ddc8c304-e505-4c8f-a1dd-fb6f5d680fd0.png">

**Comment by rougier** [comment] 2023-02-03 08:48
Can you try aligning with `scroll-bar` instead of `left-margin`?

**Comment by rougier** [comment] 2023-04-30 08:45
I mught be fixed with the new [simpler](https://github.com/rougier/nano-modeline/tree/simpler) branch. Coudl you give it a try?

**Closed by rougier** 2023-04-30 08:45 UTC
