### ISSUE TITLE
fringe inconsitancy !

### ISSUE THREAD

**Issue by vijaypanchalr3** [rougier/nano-modeline#42] opened 2022-07-06 11:04 UTC
![Screenshot from 2022-07-06 16-33-15](https://user-images.githubusercontent.com/72692300/177536350-51552e84-9aa5-4d8c-b903-26d9160cf9ce.png)

**Comment by rougier** [comment] 2022-07-11 11:28
I think the problem is [here](https://github.com/rougier/nano-modeline/blob/master/nano-modeline.el#L485=) where right part is aligned with right margin. Can you comment out `(-1 . right-margin)` and check if it solved the problem? 

Problem is that I don't remember why I added this right margin alignment.

**Comment by aaronjensen** [comment] 2022-07-11 15:12
I currently don't have that in my fork:

```el
(propertize " " 'face face-modeline 'display `(space :align-to (- right ,right-len)))
```

That's all I have and it works fine for me and this is what it looks like with window margins:
<img width="1317" alt="CleanShot 2022-07-11 at 11 10 43@2x" src="https://user-images.githubusercontent.com/8588/178296898-aa6bbe1d-e359-4b72-a579-f6264af47b82.png">

My line numbers do align to the window margin, but the gray style goes all the way to the end. That could be a face difference though... hard to diagnose this from just a screenshot.

**Comment by aaronjensen** [comment] 2022-07-11 23:16
`master` looks right to me

<img width="1917" alt="CleanShot 2022-07-11 at 19 16 18@2x" src="https://user-images.githubusercontent.com/8588/178374310-275d986a-fd6f-4e95-a9f1-c41fa248f55b.png">

**Comment by rougier** [comment] 2023-04-30 08:43
It has been fixed in the new [simpler](https://github.com/rougier/nano-modeline/tree/simpler) branch.

**Closed by rougier** 2023-04-30 08:43 UTC
